Add a formula that allows redis-stack-server to be run as a service

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -10,9 +10,9 @@ on:
   pull_request:
     branches:
       - master
+  workflow_dispatch:
 
 jobs:
-
   x86_64:
     name: Validate x86_64
     runs-on: macos-13
@@ -25,7 +25,36 @@ jobs:
       - name: run redis-stack
         run:
           /usr/local/bin/redis-stack-server -h &
-      - name: try to redis-stack
+      - name: try to ping redis-stack
+        run:
+          redis-cli ping
+
+  x86_64_service:
+    name: Validate x86_64 service
+    runs-on: macos-13
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: test in the installations
+        run: |
+          brew install --cask Casks/redis-stack-server.rb
+          brew install --formula Formula/redis-stack-service.rb
+          brew services start redis-stack-service
+      - name: wait for redis-stack service to start
+        run: |
+          attempt=1
+          max_attempts=10
+          sleep_time=2
+          until redis-cli ping 2>/dev/null || [ $attempt -gt $max_attempts ]
+          do
+            echo "Waiting for Redis Stack to start (attempt $attempt/$max_attempts)..."
+            sleep $sleep_time
+            attempt=$((attempt+1))
+          done
+          if [ $attempt -gt $max_attempts ]; then
+            echo "Redis Stack failed to start after $max_attempts attempts"
+            exit 1
+          fi
+      - name: try to ping redis-stack
         run:
           redis-cli ping
 
@@ -41,6 +70,35 @@ jobs:
       - name: run redis-stack
         run:
           /opt/homebrew/bin/redis-stack-server -h &
-      - name: try to redis-stack
+      - name: try to ping redis-stack
+        run:
+          redis-cli ping
+
+  arm64_service:
+    name: Validate arm64 service
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+      - name: test in the installations
+        run: |
+          brew install --cask Casks/redis-stack-server.rb
+          brew install --formula Formula/redis-stack-service.rb
+          brew services start redis-stack-service
+      - name: wait for redis-stack service to start
+        run: |
+          attempt=1
+          max_attempts=10
+          sleep_time=2
+          until redis-cli ping 2>/dev/null || [ $attempt -gt $max_attempts ]
+          do
+            echo "Waiting for Redis Stack to start (attempt $attempt/$max_attempts)..."
+            sleep $sleep_time
+            attempt=$((attempt+1))
+          done
+          if [ $attempt -gt $max_attempts ]; then
+            echo "Redis Stack failed to start after $max_attempts attempts"
+            exit 1
+          fi
+      - name: try to ping redis-stack
         run:
           redis-cli ping
